export default {
  FILTER_BY_NAME: 'FILTER_BY_NAME',
  FILTER_BY_LEVELS: 'FILTER_BY_LEVELS',
  FILTER_BY_SCHOOL: 'FILTER_BY_SCHOOL',
  FILTER_BY_KLASS: 'FILTER_BY_KLASS',
  READ_FROM_STORAGE: 'READ_FROM_STORAGE',
}
