import {
  GiDrinkMe,
  GiPowerRing,
  GiLunarWand,
  GiScrollUnfurled,
  GiWizardStaff,
  GiBroadsword,
  GiFluffyTrefoil,
  GiPlainDagger,
  GiAttachedShield,
  GiRobe,
  GiArmorVest,
  GiChestArmor,
  GiLeatherArmor,
  GiWoodClub,
  GiFireAxe,
  GiSpearHook,
  Gi3DHammer,
  GiFlangedMace,
  GiTelescopicBaton,
  GiSickle,
  GiCrossbow,
  GiDart,
  GiPocketBow,
  GiSling,
  GiBattleAxe,
  GiSharpAxe,
  GiFlail,
  GiGlaive,
  GiHalberd,
  GiSpearFeather,
  GiThorHammer,
  GiMaceHead,
  GiSwordHilt,
  GiTrident,
  GiClawHammer,
  GiWhip,
  GiFlatHammer,
  GiFishingNet,
  GiCrossedPistols,
} from 'react-icons/gi'
import { ImMagicWand } from 'react-icons/im'

const icons = {
  // weapons
  Weapon: <GiBroadsword size={25} />,
  Club: <GiWoodClub size={25} />,
  Greatclub: <GiWoodClub size={25} />,
  Handaxe: <GiFireAxe size={25} />,
  Javelin: <GiSpearHook size={25} />,
  'Light Hammer': <Gi3DHammer size={25} />,
  Mace: <GiFlangedMace size={25} />,
  Quarterstaff: <GiTelescopicBaton size={25} />,
  Dagger: <GiPlainDagger size={25} />,
  Sickle: <GiSickle size={25} />,
  Spear: <GiSpearHook size={25} />,
  Crossbow: <GiCrossbow size={25} />,
  Dart: <GiDart size={25} />,
  Shortbow: <GiPocketBow size={25} />,
  Sling: <GiSling size={25} />,
  Battleaxe: <GiBattleAxe size={25} />,
  Flail: <GiFlail size={25} />,
  Glaive: <GiGlaive size={25} />,
  Greataxe: <GiSharpAxe size={25} />,
  Greatsword: <GiBroadsword size={25} />,
  Halberd: <GiHalberd size={25} />,
  Lance: <GiSpearFeather size={25} />,
  Longsword: <GiBroadsword size={25} />,
  Maul: <GiThorHammer size={25} />,
  Morningstar: <GiMaceHead size={25} />,
  Rapier: <GiSwordHilt size={25} />,
  Scimitar: <GiSwordHilt size={25} />,
  Shortsword: <GiBroadsword size={25} />,
  Trident: <GiTrident size={25} />,
  'War Pick': <GiClawHammer size={25} />,
  Warhammer: <GiFlatHammer size={25} />,
  Whip: <GiWhip size={25} />,
  Blowgun: <GiDart size={25} />,
  Longbow: <GiPocketBow size={25} />,
  Net: <GiFishingNet size={25} />,
  Gun: <GiCrossedPistols size={25} />,
  // armor
  Armor: <GiLeatherArmor size={25} />,
  LightArmor: <GiLeatherArmor size={25} />,
  MediumArmor: <GiChestArmor size={25} />,
  HeavyArmor: <GiArmorVest size={25} />,
  Robe: <GiRobe size={25} />,
  Shield: <GiAttachedShield size={25} />,
  Potion: <GiDrinkMe size={25} />,
  Ring: <GiPowerRing size={25} />,
  Rod: <GiLunarWand size={25} />,
  Scroll: <GiScrollUnfurled size={25} />,
  Staff: <GiWizardStaff size={25} />,
  Wand: <ImMagicWand size={25} />,
  'Wondrous Item': <GiFluffyTrefoil size={25} />,
}

export { icons as default }
