import {
  GiDrinkMe,
  GiPowerRing,
  GiLunarWand,
  GiScrollUnfurled,
  GiWizardStaff,
  GiBroadsword,
  GiFluffyTrefoil,
  GiPlainDagger,
  GiShield,
  GiRobe,
  GiArmorVest,
  GiChestArmor,
  GiLeatherArmor,
  GiWoodClub,
  GiFireAxe,
  GiSpearHook,
  Gi3DHammer,
  GiFlangedMace,
  GiTelescopicBaton,
  GiSickle,
  GiCrossbow,
  GiDart,
  GiPocketBow,
  GiSling,
  GiBattleAxe,
  GiSharpAxe,
  GiFlail,
  GiGlaive,
  GiHalberd,
  GiSpearFeather,
  GiThorHammer,
  GiMaceHead,
  GiSwordHilt,
  GiTrident,
  GiClawHammer,
  GiWhip,
  GiFlatHammer,
  GiFishingNet,
  GiCrossedPistols,
} from 'react-icons/gi'
import { ImMagicWand } from 'react-icons/im'

const icons = {
  // weapons
  Weapon: <GiBroadsword size={25} color="#eeeeee" />,
  Club: <GiWoodClub size={25} color="#eeeeee" />,
  Greatclub: <GiWoodClub size={25} color="#eeeeee" />,
  Handaxe: <GiFireAxe size={25} color="#eeeeee" />,
  Javelin: <GiSpearHook size={25} color="#eeeeee" />,
  'Light Hammer': <Gi3DHammer size={25} color="#eeeeee" />,
  Mace: <GiFlangedMace size={25} color="#eeeeee" />,
  Quarterstaff: <GiTelescopicBaton size={25} color="#eeeeee" />,
  Dagger: <GiPlainDagger size={25} color="#eeeeee" />,
  Sickle: <GiSickle size={25} color="#eeeeee" />,
  Spear: <GiSpearHook size={25} color="#eeeeee" />,
  Crossbow: <GiCrossbow size={25} color="#eeeeee" />,
  Dart: <GiDart size={25} color="#eeeeee" />,
  Shortbow: <GiPocketBow size={25} color="#eeeeee" />,
  Sling: <GiSling size={25} color="#eeeeee" />,
  Battleaxe: <GiBattleAxe size={25} color="#eeeeee" />,
  Flail: <GiFlail size={25} color="#eeeeee" />,
  Glaive: <GiGlaive size={25} color="#eeeeee" />,
  Greataxe: <GiSharpAxe size={25} color="#eeeeee" />,
  Greatsword: <GiBroadsword size={25} color="#eeeeee" />,
  Halberd: <GiHalberd size={25} color="#eeeeee" />,
  Lance: <GiSpearFeather size={25} color="#eeeeee" />,
  Longsword: <GiBroadsword size={25} color="#eeeeee" />,
  Maul: <GiThorHammer size={25} color="#eeeeee" />,
  Morningstar: <GiMaceHead size={25} color="#eeeeee" />,
  Rapier: <GiSwordHilt size={25} color="#eeeeee" />,
  Scimitar: <GiSwordHilt size={25} color="#eeeeee" />,
  Shortsword: <GiBroadsword size={25} color="#eeeeee" />,
  Trident: <GiTrident size={25} color="#eeeeee" />,
  'War Pick': <GiClawHammer size={25} color="#eeeeee" />,
  Warhammer: <GiFlatHammer size={25} color="#eeeeee" />,
  Whip: <GiWhip size={25} color="#eeeeee" />,
  Blowgun: <GiDart size={25} color="#eeeeee" />,
  Longbow: <GiPocketBow size={25} color="#eeeeee" />,
  Net: <GiFishingNet size={25} color="#eeeeee" />,
  Gun: <GiCrossedPistols size={25} color="#eeeeee" />,
  // armor
  Armor: <GiLeatherArmor size={25} color="#eeeeee" />,
  LightArmor: <GiLeatherArmor size={25} color="#eeeeee" />,
  MediumArmor: <GiChestArmor size={25} color="#eeeeee" />,
  HeavyArmor: <GiArmorVest size={25} color="#eeeeee" />,
  Robe: <GiRobe size={25} color="#eeeeee" />,
  Shield: <GiShield size={25} color="#eeeeee" />,
  Potion: <GiDrinkMe size={25} color="#eeeeee" />,
  Ring: <GiPowerRing size={25} color="#eeeeee" />,
  Rod: <GiLunarWand size={25} color="#eeeeee" />,
  Scroll: <GiScrollUnfurled size={25} color="#eeeeee" />,
  Staff: <GiWizardStaff size={25} color="#eeeeee" />,
  Wand: <ImMagicWand size={25} color="#eeeeee" />,
  'Wondrous Item': <GiFluffyTrefoil size={25} color="#eeeeee" />,
}

export { icons as default }
