import { Character } from '../generated/graphql'

export type CharacterModel = Pick<
  Character,
  | 'id'
  | 'name'
  | 'armorClass'
  | 'level'
  | 'race'
  | 'klass'
  | 'hitPoints'
  | 'maxHitPoints'
  | 'arcaneWard'
  | 'arcaneWardMax'
  | 'alignment'
  | 'gold'
  | 'magicItems'
  | 'inspiration'
  | 'strength'
  | 'dexterity'
  | 'intelligence'
  | 'wisdom'
  | 'charisma'
  | 'constitution'
  | 'skills'
  | 'speed'
  | 'spellSlots'
  | 'klassAbilityOne'
  | 'subclass'
  | 'spells'
  | 'preparedSpells'
>
